remote_theme: "mmistakes/minimal-mistakes"

title: "TextUp"
title_separator: "|"
description: "TextUp provides mobile communication and collaboration for social services"
url: "https://www.textup.org"
repository: "TextUp/textup.github.io"
search: true
github: [metadata]

# Caution: Inline JavaScript comments can cause problems with compress.html, so be sure to
# /* comment this way */ and avoid // these sorts of comments.
compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

sass:
    sass_dir: _sass

plugins:
  - jekyll-remote-theme

collections:
  articles:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: single
      read_time: true
      toc: true
      toc_label: "In this article"
      sidebar:
        nav: "articles"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      author: TextUp
      read_time: true
      comments: false
      share: false
      related: false
